// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.
/*global Whiteboard*/
Whiteboard.mainPage = SC.Page.design({
  mainPane: SC.MainPane.design({
    childViews: 'canvas'.w(),
    canvas: Whiteboard.Canvas.design({
      linesBinding: 'Whiteboard.pathsController'
    })    
  }),
  
  startPane: SC.Pane.design({
    render: function(context, firstTime){
      context.begin('center')
      .begin('h1').text('Welcome To Whiteboard').end()
      .begin('h3').text('begin a new session or join...').end()
      .begin('h1').id('new').addStyle({'backgroundColor': 'white', 'width': '40px'})
      .text('New').end()
      
      .begin('p').addStyle({paddingTop: '10px'})
        .begin('input').id('key').attr({type: 'text', autocomplete: 'off'}).end()
        .begin('h1').id('join').addStyle({'backgroundColor': 'white', 'width': '40px'})
        .text('Join').end()
        .end()
      .end();
    },
    touchStart: function(evt){
      console.log('touch start');
      var target = evt.target ? evt.target : evt.event.target;
      var id = target.id ? target.id : target.parentNode.id;
      
      if(id === 'new' || id === 'join') return YES;
      else return NO;
    },
    touchesDragged: function(){
      return YES;
    },
    touchEnd: function(evt){
      var target = evt.target ? evt.target : evt.event.target;
      var id = target.id ? target.id : target.parentNode.id;
      
      
      if(id === 'new'){
        Whiteboard.createNew();
      }
      else if(id === 'join'){
        Whiteboard.requestJoinBoard(this.$('#key')[0].value);
      }
      return YES;
    },
    
    mouseDown: function(evt){
      return this.touchStart(evt);
    },
    mouseUp: function(evt){
      return this.touchEnd(evt);
    }

  }),
  pageName: "Whiteboard.mainPage"
});
